Get info and settings only once, assist user w/ conf, various fixes
I apologize for a quite messy patch. Some things were worked on in
parallel here for various reasons.

This patch will verify that a client configuration exists before
proceeding, and will offer to help create one if a machine with a
corresponding name is found.

This patch will also verify that there is an actual machine
corresponding to the specified client.

diff --git a/scripts/generate-conf b/scripts/generate-conf
--- a/scripts/generate-conf
+++ b/scripts/generate-conf
@@ -32,7 +32,6 @@ echo_vbox_client_conf()
     echo VM_SUPERUSER=root
     echo SSH_PORT=auto
     echo SSH_SHUTDOWN_COMMAND=\"shutdown -h now\"
-
 }
 
 echo_android_client_conf()
@@ -58,7 +57,6 @@ echo_android_client_conf()
 	echo "Unsupported CPU"
     fi
     echo "ANDROID_SYS=$ANDROID_SYS"
-
     echo "#CPU_ARCH=$CPU_ARCH"
     echo "#CPU_MODEL=$CPU_MODEL"
 }
@@ -72,7 +70,9 @@ create_vbox_client_conf()
 
     if [ -f $CONF_NAME ]
 	then
-	echo "Configuration file for $VM_MACHINE already exists"
+	debug "Configuration file for \"$VM_MACHINE\" already exists."
+	debug "   $CONF_NAME"
+	echo "Configuration file for \"$VM_MACHINE\" already exists."
 	echo "   $CONF_NAME"
 	return 1
     fi
@@ -82,10 +82,15 @@ create_vbox_client_conf()
 	mkdir -p ${PERSONAL_ETC_DIR}/clients
     fi
 
-    echo "Creating $CONF_NAME"
-
     echo_vbox_client_conf "$VM_MACHINE" > $CONF_NAME
-
+    if [ $? = 0 ] ; then
+	debug "Created conf for vbox \"VM_MACHINE\"."
+	echo "Created $CONF_NAME"
+    else
+	debug "Failed to create conf for vbox \"VM_MACHINE\"."
+	echo "Failed to create conf for vbox \"VM_MACHINE\"."
+    fi
+    return $?
 }
 
 create_android_client_conf()
@@ -97,7 +102,7 @@ create_android_client_conf()
 
     if [ -f $CONF_NAME ]
 	then
-	echo "Configuration file for $VM_MACHINE already exists"
+	echo "Configuration file for \"$VM_MACHINE\" already exist.s"
 	echo "   $CONF_NAME"
 	return 1
     fi
@@ -107,10 +112,15 @@ create_android_client_conf()
 	mkdir -p ${PERSONAL_ETC_DIR}/clients
     fi
 
-    echo "Creating $CONF_NAME"
-
     echo_android_client_conf $VM_MACHINE > $CONF_NAME
-
+    if [ $? = 0 ] ; then
+	debug "Created conf for android \"VM_MACHINE\"."
+	echo "Created $CONF_NAME"
+    else
+	debug "Failed to create conf for android \"VM_MACHINE\"."
+	echo "Failed to create conf for android \"VM_MACHINE\"."
+    fi
+    return $?
 }
 
 
@@ -118,20 +128,22 @@ create_client_conf()
 {
     VM_MACHINE="$1"
 
-    find_vm_type $VM_MACHINE
+    find_vm_type "$VM_MACHINE"
 
     if [ "$VM_TYPE" = "" ]
     then
-	echo "Couldn't find type for machine \"$VM_MACHINE\""
+	echo "Couldn't find type for machine \"$VM_MACHINE\"."
+	return 1
     elif [ "$VM_TYPE" = "VirtualBox" ]
     then
 	create_vbox_client_conf "$VM_MACHINE"
+	return $?
     elif [ "$VM_TYPE" = "Android" ]
     then
-	create_android_client_conf $VM_MACHINE
-	
+	create_android_client_conf "$VM_MACHINE"
+	return $?
     else
-	echo "Can't create conf for $VM_MACHINE ($VM_TYPE)"
+	echo "Can't create conf for \"$VM_MACHINE\" ($VM_TYPE)."
+	return 1
     fi
-
 }
