Continue various minor enhancements to client code
Removed unnecessary "for" loop in function `get_info_for_client'.

Improved `get_vbox_specific_info()' by added debug logging, a variable MY_VM for clarification and coherence, added checking of existence of the virtual machine at the beginning of the function, and rerranged the structure of the code. Also changed the variable name from TMP_CLIENTS to CLI_CONF, and introduced a new variable STATE to track the state of the two booleans.

Improved `get_android_specific_info()' by removing ANDROID_SYS=$( grep ANDROID_SYS $CLI_CONF | sed 's,ANDROID_SYS=,,g' | sed 's,\",,g'). This is done because ANDROID_SYS is set in the configuration file in the scripts/functions script.

diff --git a/scripts/vmm-client-functions b/scripts/vmm-client-functions
--- a/scripts/vmm-client-functions
+++ b/scripts/vmm-client-functions
@@ -769,6 +769,7 @@ stop_client()
 
 pause_client()
 {
+    debug "Start debugging: --pause-client"
     CLIENT_FOUND=false
     WANTED_VM=$1
     START_ARGS=$2
@@ -1676,28 +1677,48 @@ check_machine_android()
 
 get_vbox_specific_info()
 {
-#	echo find ssh port
-#	echo	vboxmanage   showvminfo $VM_NAME 
-    if [ "$SSH_PORT" = "auto" ]
+    MY_VM=$1
+    debug "Try to find virtual machine: $MY_VM."
+    if [ 0 -eq $(vboxmanage list vms | awk ' { printf "%s\n", $MY_VM }' | grep "\"$MY_VM\"" | wc -l) ]
     then
-	SSH_PORT=$(vboxmanage   showvminfo $VM_NAME 2>/dev/null | grep "NIC" | grep -e Rule -e ssh | grep 22 | grep "host port" | sed 's,[a-zA-Z0-9,: \ =()]*host port[ \t]*=,,g' | awk '{print $1}' | sed 's/,//g' )
-    fi
+	debug "Could not find virtual machine: $MY_VM"
+	echo "Could not find virtual machine: $MY_VM"
+	return 1
+    else
+	debug "Virtual machine $MY_VM has been found."
+	debug "Set ssh port for $MY_VM."
+	if [ "$SSH_PORT" = "auto" ]
+	then
+	    SSH_PORT=$(vboxmanage showvminfo $VM_NAME 2>/dev/null | grep "NIC" | grep -e Rule -e ssh | grep 22 | grep "host port" | sed 's,[a-zA-Z0-9,: \ =()]*host port[ \t]*=,,g' | awk '{print $MY_VM}' | sed 's/,//g' )
+	    return 0
+	fi
 
-    if [ "$SSH_PORT" = "" ]
-    then
-	debug "SSH_PORT is not set."
+	if [ "$SSH_PORT" = "" ]
+	then
+	    debug "SSH_PORT is not specified in the configuration file."
+	    return 1
+	fi
+
+	debug "SSH_PORT is NOT set to auto NOR null. Return 1"
 	return 1
     fi
-
-#    echo "SSH_PORT=$SSH_PORT"
-    return 0
 }
 
 get_android_specific_info()
 {
-    MY_VM="$1"
-    ANDROID_SYS=$( grep ANDROID_SYS $CLI_CONF | sed 's,ANDROID_SYS=,,g' | sed 's,\",,g')
+    MY_VM=$1
+    debug "Try to find Android emulator: $MY_VM"
+    # The following command only works when the avd is running.
+    # So I am going to add a functionality to enable 
+    # get_android_specific_info()
+    # to check if there is an avd matches the $WANTED_CLIENT
+    # when there is no avd running.
     ANDROID_PORT=$(get_avd_port_for_name $MY_VM)
+    debug "ANDROID_PORT:  $ANDROID_PORT"
+
+#   List all avds
+#   $ANDROID list avd | grep Name | sed 's,[ \t]*Name: ,,g' | grep "$1"
+
 }
 
 get_vm_specific_info()
@@ -1706,7 +1727,7 @@ get_vm_specific_info()
     RET=1
     if [ "$VM_TYPE" = "VirtualBox" ]
     then
-	get_vbox_specific_info
+	get_vbox_specific_info $MY_VM
 	RET=$?
     elif [ "$VM_TYPE" = "Android" ]
     then
@@ -1723,33 +1744,74 @@ get_info_for_client()
 {
     debug "Trying to get info for client: $1"
     WANTED_CLIENT=$1
+    CONF_READY=false
+    MACHINE_READY=false
+
+    # CLIENT_FOUND == true only when 
+    # CONF_READY == true && MACHINE_FOUND == true
     CLIENT_FOUND=false
+    STATE=false
+
+    debug "Looking for $WANTED_CLIENT.conf at following paths."
+    debug "$ETC_DIRS"
     for ETC_DIR in $ETC_DIRS
     do
-	TMP_CLIENTS=$(find $ETC_DIR/clients -name "$WANTED_CLIENT.conf" 2>/dev/null)
-	for i in $TMP_CLIENTS
-	do    
-	    export VM_NAME=$(grep VM_NAME $i | sed -e 's,VM_NAME=,,g' -e 's,\",,g' )
-	    CLI_CONF=$i
+	CLI_CONF=$(find $ETC_DIR/clients -name "$WANTED_CLIENT.conf" 2>/dev/null)
 
-	    . $CLI_CONF
-	   
-	    CLIENT_FOUND=true
-
-	    get_vm_specific_info $VM_NAME
-	    RET=$?
-	    if [ $RET -ne 0 ] ; then debug "Client seems to be down"; CLIENT_FOUND=false; fi
-	
-	    if [ "$CLIENT_FOUND" = "true" ]
-	    then
-		debug "  got info for $1: $VM_NAME, $VM_TYPE, $CLI_CONF"
-		return 0
-	    fi
-
-	done
+	if [ -f $CLI_CONF ]
+	then
+	    debug "Client $WANTED_CLIENT has been found."
+	    debug "$CLI_CONF"
+	    . "$CLI_CONF"
+	    CONF_READY=true
+	    break
+	else
+	    debug "Client $WANTED_CLIENT can not be found."
+	    CONF_READY=false
+	fi
     done
-    debug "  got no info for $1"
-    return 1
+    
+    debug "Checking virtual machine: $WANTED_CLIENT"
+    get_vm_specific_info $VM_NAME
+
+    RET=$?
+    debug "$RET"
+    if [ $RET -ne 0 ]
+    then
+	debug "Machine seems to be down."
+	MACHINE_READY=false
+    else
+	MACHINE_READY=true
+    fi
+    
+    STATE=$CONF_READY$MACHINE_READY
+    debug "STATE: $STATE"
+    case "$STATE" in
+	truetrue)
+	    debug "Got info for $WANTED_CLIENT: $VM_NAME, $VM_TYPE, $CLI_CONF"
+	    CLIENT_FOUND=true
+	    return 0
+	    ;;
+
+	truefalse)
+	    debug "conf is found but vm is not ready."
+	    return 1
+	    ;;
+
+	falsetrue)
+	    debug "Counld not find conf for vm."
+	    return 1
+	    ;;
+
+	falsefalse)
+	    debug "Got no info for $WANTED_CLIENT"
+	    return 1
+	    ;;
+
+	*)
+	    echo "Something wrong!"
+	    return 1
+    esac
 }
 
 
