Fixes #13   .... and more flexible android checks

diff --git a/scripts/vmm-client-android-specific b/scripts/vmm-client-android-specific
--- a/scripts/vmm-client-android-specific
+++ b/scripts/vmm-client-android-specific
@@ -40,6 +40,10 @@ get_avd_port_for_name()
 
 get_connected_avds() 
 {
+    check_android_settings hard
+    RET=$?
+    if [ $RET -ne 0 ] ; then return $RET; fi
+
     $ADB devices | grep -v "List of devices attached" | \
 	grep -v "^[ \t]*$"   | \
 	awk ' { print $1 } ' | \
@@ -51,9 +55,9 @@ get_connected_avds_ports()
     get_connected_avds | sed -e "s,[ \t]*emulator\-,,g" 
 }
 
-check_android_settings()
-{
 
+setup_android()
+{
     # Set up Android path stuff
     if [ "$ANDROID_ADT_PATH" != "" ] && [ "$ANDROID" != "" ]
     then   	 
@@ -75,31 +79,44 @@ check_android_settings()
     then   	 
 	ADB=$ANDROID_ADT_PATH/sdk/platform-tools/adb2
     fi
+}
 
-##  
+check_android_settings()
+{
+    CHECK_MODE=$1
 
     if [ "$ANDROID" = "" ] || [ ! -x $ANDROID ]
     then   	 
-	echo "no android command found"
+	if [ "$CHECK_MODE" = "true" ] ; then
+	    echo "no android command found"
+	fi
+	debug "no android command found"
 	return 1
     fi
 
 
     if [ "$ADB" = "" ] || [ ! -x $ADB ]
     then   	 
-	echo "no adb command found"
+	if [ "$CHECK_MODE" = "true" ] ; then
+	    echo "no android command found"
+	fi
+	debug "no adb command found"
 	return 1
     fi
 
 
     if [ "$ANDROID_ADT_PATH" = "" ]
     then   	 
-	echo "Can't find Android adt ... you must set ANDROID_ADT_PATH in your vmm.conf"
+	if [ "$CHECK_MODE" = "true" ] ; then
+	    echo "Can't find Android adt ... you must set ANDROID_ADT_PATH in your vmm.conf"
+	fi
+	debug "Can't find Android adt ... you must set ANDROID_ADT_PATH in your vmm.conf"
 	return 1
     fi
 
     return 0
 }
+
 
 
 exec_client_command_android()
@@ -112,6 +129,10 @@ exec_client_command_android()
 
     PORT=$1
     COMMAND="$2"
+
+    check_android_settings hard
+    RET=$?
+    if [ $RET -ne 0 ] ; then return $RET; fi
 
     debug "Will execute on Android ($PORT):  $COMMAND"
     $ADB  -s emulator-$PORT shell $COMMAND
@@ -128,6 +149,10 @@ exec_client_raw_android()
 
     PORT=$1
     COMMAND="$2"
+
+    check_android_settings hard
+    RET=$?
+    if [ $RET -ne 0 ] ; then return $RET; fi
 
     debug "Will execute on Android ($PORT):  $COMMAND"
     $ADB  -s emulator-$PORT $COMMAND
diff --git a/scripts/vmm-client-functions b/scripts/vmm-client-functions
--- a/scripts/vmm-client-functions
+++ b/scripts/vmm-client-functions
@@ -70,7 +70,7 @@ list_vbox_machines()
 
 list_android_machines()
 {
-    check_android_settings
+    check_android_settings hard
     RET=$?
     if [ $RET -ne 0 ] ; then return $RET; fi
 
@@ -447,14 +447,37 @@ start_android()
     export PROC_EXPR=$1
     debug "Start android: $VM_NAME"
 
-    $ANDROID_ADT_PATH/sdk/tools/$ANDROID_SYS -avd $PROC_EXPR  -netspeed full -netdelay none &
+    check_android_settings hard
+    if [ "$?" != "0" ] ; then
+	echo "Android commands doesn't seem to be set up correctly."
+	return 1
+    fi 
 
+    if [ ! -x $ANDROID_ADT_PATH/sdk/tools/$ANDROID_SYS ] ; then
+	echo "Android commands doesn't seem to be set up correctly."
+	echo "Could not find $ANDROID_ADT_PATH/sdk/tools/$ANDROID_SYS"
+	return 1
+    fi
+
+    $ANDROID_ADT_PATH/sdk/tools/$ANDROID_SYS -avd $PROC_EXPR  -netspeed full -netdelay none &
 }
 
 start_android_headless()
 {
     export PROC_EXPR=$1
     debug "Start android in headless mode: $VM_NAME"
+
+    check_android_settings hard
+    if [ "$?" != "0" ] ; then
+	echo "Android commands doesn't seem to be set up correctly."
+	return 1
+    fi 
+
+    if [ ! -x $ANDROID_ADT_PATH/sdk/tools/$ANDROID_SYS ] ; then
+	echo "Android commands doesn't seem to be set up correctly."
+	echo "Could not find $ANDROID_ADT_PATH/sdk/tools/$ANDROID_SYS"
+	return 1
+    fi
 
     $ANDROID_ADT_PATH/sdk/tools/$ANDROID_SYS -avd $PROC_EXPR  -netspeed full -netdelay none -no-window &
 }
@@ -586,10 +609,24 @@ stop_android()
     VB_NAME=$1
     debug "Stopping Android $VM_NAME"
 
+    check_android_settings hard
+    if [ "$?" != "0" ] ; then
+	echo "Android commands doesn't seem to be set up correctly."
+	return 1
+    fi 
+
+    if [ ! -x $ADB ] ; then
+	echo "Android commands doesn't seem to be set up correctly."
+	echo "Could not find adb"
+	return 1
+    fi
+
+
+
     if [ "$VB_NAME" != "" ]
     then
 	debug "Killing Android $VB_NAME"
-	adb  -s emulator-$ANDROID_PORT emu kill  >/dev/null 2>/dev/null
+	$ADB  -s emulator-$ANDROID_PORT emu kill  >/dev/null 2>/dev/null
 	
 	wait_for_state down 20 $VB_NAME
 
@@ -1134,6 +1171,20 @@ is_android_up()
 {
     export WANTED_VM=$1
 
+
+    check_android_settings hard
+    if [ "$?" != "0" ] ; then
+	echo "Android commands doesn't seem to be set up correctly."
+	return 1
+    fi 
+
+    if [ ! -x $ADB ] ; then
+	echo "Android commands doesn't seem to be set up correctly."
+	echo "Could not find adb"
+	return 1
+    fi
+
+
     debug "    get_info_for_client $1"
     get_info_for_client "$1"
 
@@ -1144,7 +1195,7 @@ is_android_up()
     fi
 
     debug "    is_android_up? adb  -s emulator-$ANDROID_PORT shell ls"
-    adb  -s emulator-$ANDROID_PORT shell ls >/dev/null 2>/dev/null
+    $ADB  -s emulator-$ANDROID_PORT shell ls >/dev/null 2>/dev/null
     RET=$?
     
     debug "    is_android_up: $CNT"
@@ -1792,9 +1843,21 @@ vbox_snapshot()
 
 android_snapshot()
 {
+    check_android_settings hard
+    if [ "$?" != "0" ] ; then
+	echo "Android commands doesn't seem to be set up correctly."
+	return 1
+    fi 
+
+    if [ ! -x $ADB ] ; then
+	echo "Android commands doesn't seem to be set up correctly."
+	echo "Could not find adb"
+	return 1
+    fi
+
 
     # COmmand line fron http://blog.shvetsov.com/2013/02/grab-android-screenshot-to-computer-via.html
-    adb  -s emulator-$1 shell screencap -p | perl -pe 's/\x0D\x0A/\x0A/g' > $2
+    $ADB  -s emulator-$1 shell screencap -p | perl -pe 's/\x0D\x0A/\x0A/g' > $2
 }
 
 rename_screenshot_name()
@@ -1953,9 +2016,21 @@ copy_from_host()
 	    ;;
     
 	"Android")
+
+	    check_android_settings hard
+	    if [ "$?" != "0" ] ; then
+		echo "Android commands doesn't seem to be set up correctly."
+		return 1
+	    fi 
+	    
+	    if [ ! -x $ADB ] ; then
+		echo "Android commands doesn't seem to be set up correctly."
+		echo "Could not find adb"
+		return 1
+	    fi
 	    debug "copy android"
 	    debug "     adb  -s emulator-$ANDROID_PORT pull $MY_SRC_LOC $MY_DST_LOC"
-	    adb  -s emulator-$ANDROID_PORT pull $MY_SRC_LOC $MY_DST_LOC
+	    $ADB  -s emulator-$ANDROID_PORT pull $MY_SRC_LOC $MY_DST_LOC
 	    ;;
 	*)
 	    echo "copy not supported"
@@ -1989,9 +2064,21 @@ copy_to_host()
 	    ;;
     
 	"Android")
+
+	    check_android_settings hard
+	    if [ "$?" != "0" ] ; then
+		echo "Android commands doesn't seem to be set up correctly."
+		return 1
+	    fi 
+
+	    if [ ! -x $ADB ] ; then
+		echo "Android commands doesn't seem to be set up correctly."
+		echo "Could not find adb"
+		return 1
+	    fi
 	    debug "copy android"
 	    debug "     adb  -s emulator-$ANDROID_PORT push $MY_SRC_LOC $MY_DST_LOC"
-	    adb  -s emulator-$ANDROID_PORT push $MY_SRC_LOC $MY_DST_LOC
+	    $ADB  -s emulator-$ANDROID_PORT push $MY_SRC_LOC $MY_DST_LOC
 	    ;;
 	*)
 	    echo "copy not supported"
