Android: getting port and name from attached devices.  Andoird+VBox: better printing of running machines

diff --git a/scripts/vmm-client-functions b/scripts/vmm-client-functions
--- a/scripts/vmm-client-functions
+++ b/scripts/vmm-client-functions
@@ -27,7 +27,14 @@ export SCRIPTS_TO_EXECUTE
 ANDROID_AVD_DIR=${HOME}/.android/avd/
 ANDROID_ADT_PATH=/home/hesa/opt/adt-bundle-linux-x86_64-20130219
 
-
+ANDROID_SPEC_FILE=$(dirname $0)/../share/testingmachine/scripts/vmm-client-android-specific
+if [ -f $ANDROID_SPEC_FILE ]
+then
+    source $ANDROID_SPEC_FILE
+else
+    echo "Can't find $ANDROID_SPEC_FILE"
+    exit 1
+fi
 
 list_vbox_machines()
 {
@@ -61,6 +68,7 @@ list_vbox_machines()
 	fi
     done
 }
+
 
 list_android_machines()
 {
@@ -141,17 +149,23 @@ list_running_vbox()
     VB_NAME=$(vboxmanage list runningvms | awk ' { printf "%s", $1}' | sed 's,\",,g')
     if [ "$VB_NAME" != "" ]
     then
-	echo "  |--$VB_NAME  which is used in"
-	for dir in  $ETC_DIRS
+	for i in $VB_NAME
 	do
-	    if [ -d $dir ]
-	    then
-		for vb in $(find $dir/clients -name *.conf | xargs grep -l $VB_NAME )
-		do
-		    VB_SHORT_NAME=$(basename $vb)
-		    echo "    |--$VB_SHORT_NAME  [$vb]"  
-		done
-	    fi
+	    echo "  |--$i  "
+	    FOUND=0
+	    for dir in  $ETC_DIRS
+	    do
+		if [ -d $dir ]
+		then
+		    for vb in $(find $dir/clients -name *.conf | xargs grep -l $i )
+		    do
+			VB_SHORT_NAME=$(basename $vb)
+			echo "    |--$VB_SHORT_NAME  [$vb] (client)"  
+			FOUND=1
+		    done
+		fi
+	    done
+	    if [ $FOUND -eq 0 ] ; then echo "    * avd is not in use"; fi
 	done
     else
 	echo "   no virtualbox machines currently running"
@@ -161,20 +175,28 @@ list_running_vbox()
 list_running_android()
 {
     echo "  Android"
-    VB_NAME=$(adb devices | grep -v "List of devices attached" | awk ' { printf "%s", $1}' | sed 's,\",,g')
+    VB_NAME=$(get_connected_avds_ports)
     if [ "$VB_NAME" != "" ]
     then
-	echo "  |--$VB_NAME  which is used in"
-	for dir in  $ETC_DIRS
+	for i in $VB_NAME
 	do
-	    if [ -d $dir ]
-	    then
-		for vb in $(find $dir/clients -name *.conf | xargs grep -l $VB_NAME )
-		do
-		    VB_SHORT_NAME=$(basename $vb)
-		    echo "    |--$VB_SHORT_NAME  [$vb]"  
+	    AVD_NAME=$(get_avd_name_for_port $i)
+	    echo "  |-- $AVD_NAME  (using port $i)"
+
+	    FOUND=0
+	    for dir in  $ETC_DIRS
+	    do
+		if [ -d $dir ]
+		then
+		    for vb in $(find $dir/clients -name *.conf | xargs grep -l $AVD_NAME )
+		    do
+			VB_SHORT_NAME=$(basename $vb)
+			echo "    |--$VB_SHORT_NAME  [$vb] (client)"  
+			FOUND=1
 		done
-	    fi
+		fi
+	    done
+	    if [ $FOUND -eq 0 ] ; then echo "    * avd is not in use"; fi
 	done
     else
 	echo "   no virtualbox machines currently running"
